version: "3.2"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    volumes:
      - "./src/:/var/www/html/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "8080:80"
  mysql-server:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5000:80"
volumes:
  mysql-data:
